-- MOJANG ULP Samboja — production schema for Supabase/Postgres
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  fullname text not null,
  role text not null default 'Staff' check (role in ('Admin', 'Staff')),
  created_at timestamptz not null default now()
);

create table if not exists public.pelanggan (
  id uuid primary key default gen_random_uuid(),
  idpel text not null unique check (char_length(idpel) between 8 and 24),
  nama text not null,
  gardu text not null,
  feeder text not null check (feeder in ('SNP.01', 'SNP.02', 'SNP.03', 'SNP.04', 'KRJ13', 'MJW 01')),
  tarif text not null,
  daya bigint not null default 0 check (daya >= 0),
  beban_siang numeric(12,2) not null default 0 check (beban_siang >= 0),
  beban_malam numeric(12,2) not null default 0 check (beban_malam >= 0),
  tgl_inspeksi date not null default current_date,
  keterangan text not null default 'NYALA',
  created_by uuid references auth.users(id) on delete set null default auth.uid(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists pelanggan_feeder_idx on public.pelanggan(feeder);
create index if not exists pelanggan_tgl_inspeksi_idx on public.pelanggan(tgl_inspeksi desc);
create index if not exists pelanggan_nama_lower_idx on public.pelanggan(lower(nama));

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity text not null,
  entity_id uuid,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists pelanggan_touch_updated_at on public.pelanggan;
create trigger pelanggan_touch_updated_at
before update on public.pelanggan
for each row execute function public.touch_updated_at();

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, username, fullname, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data ->> 'username', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data ->> 'fullname', split_part(new.email, '@', 1)),
    case when new.raw_user_meta_data ->> 'role' = 'Admin' then 'Admin' else 'Staff' end
  )
  on conflict (id) do update set
    username = excluded.username,
    fullname = excluded.fullname,
    role = excluded.role;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert or update of raw_user_meta_data on auth.users
for each row execute function public.handle_new_user();

create or replace function public.log_pelanggan_change()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  affected_id uuid;
  snapshot jsonb;
begin
  affected_id := coalesce(new.id, old.id);
  snapshot := case when tg_op = 'DELETE' then to_jsonb(old) else to_jsonb(new) end;
  insert into public.audit_logs (actor_id, action, entity, entity_id, detail)
  values (auth.uid(), tg_op, 'pelanggan', affected_id, snapshot - 'created_by');
  return coalesce(new, old);
end;
$$;

drop trigger if exists pelanggan_audit_change on public.pelanggan;
create trigger pelanggan_audit_change
after insert or update or delete on public.pelanggan
for each row execute function public.log_pelanggan_change();

alter table public.profiles enable row level security;
alter table public.pelanggan enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "profiles_read_own" on public.profiles;
create policy "profiles_read_own" on public.profiles
for select to authenticated
using (id = auth.uid());

drop policy if exists "pelanggan_read_authenticated" on public.pelanggan;
create policy "pelanggan_read_authenticated" on public.pelanggan
for select to authenticated
using (true);

drop policy if exists "pelanggan_insert_authenticated" on public.pelanggan;
create policy "pelanggan_insert_authenticated" on public.pelanggan
for insert to authenticated
with check (auth.uid() is not null);

drop policy if exists "pelanggan_update_authenticated" on public.pelanggan;
create policy "pelanggan_update_authenticated" on public.pelanggan
for update to authenticated
using (true)
with check (true);

drop policy if exists "pelanggan_delete_admin" on public.pelanggan;
create policy "pelanggan_delete_admin" on public.pelanggan
for delete to authenticated
using (exists (
  select 1 from public.profiles
  where profiles.id = auth.uid() and profiles.role = 'Admin'
));

drop policy if exists "audit_read_admin" on public.audit_logs;
create policy "audit_read_admin" on public.audit_logs
for select to authenticated
using (exists (
  select 1 from public.profiles
  where profiles.id = auth.uid() and profiles.role = 'Admin'
));

grant usage on schema public to authenticated;
grant select on public.profiles to authenticated;
grant select, insert, update, delete on public.pelanggan to authenticated;
grant select on public.audit_logs to authenticated;
grant usage, select on all sequences in schema public to authenticated;

create or replace view public.feeder_summary
with (security_invoker = true)
as
select
  feeder,
  count(*)::int as total_pelanggan,
  sum(daya)::bigint as total_daya,
  sum(beban_siang)::numeric as total_beban_siang,
  sum(beban_malam)::numeric as total_beban_malam
from public.pelanggan
group by feeder;

grant select on public.feeder_summary to authenticated;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'pelanggan'
  ) then
    alter publication supabase_realtime add table public.pelanggan;
  end if;
end $$;
